<template>
  <section class="container transfer-page">
    <header class="transfer-heading"><h1>上傳檔案</h1><p>請依照以下 FTP 傳檔步驟操作；完成傳輸後，請來電或傳真告知。</p></header>
    <section class="ftp-intro"><div><h2>FTP 傳檔</h2><p>請先安裝 FileZilla，再依照下方步驟連線並上傳檔案。</p></div><a class="btn" href="http://www.imagecopy.com.tw/FTP連線程式.rar" target="_blank" rel="noopener">下載 FileZilla <span>→</span></a></section>
    <section class="transfer-notes" aria-labelledby="transfer-notes-title"><h2 id="transfer-notes-title">傳檔注意事項</h2><ol><li>FTP 傳檔無法上傳整個資料夾，請壓縮後再傳，或將檔案複製後貼上。</li><li>PDF 檔可跨平台使用，建議將 Word 與 Excel 檔案轉存為 PDF 格式，避免不同平台造成錯誤。</li><li>使用 MAC 電腦系統時，請務必將圖檔轉換為 PC 格式，避免上傳後無法讀取。</li><li>顏色以 CMYK 為依據，不可用螢幕顏色要求印刷顏色；螢幕顏色不一定準確。</li><li>文字請全部轉成曲線或建立外框；如使用特殊字型，請一併附上字型。</li><li>上傳前請先自行備份檔案，本店不負責上傳檔案損壞或遺失的風險。</li><li>建議使用 PDF、Word、CorelDraw、Illustrator、Photoshop 等檔案格式。</li></ol><p class="transfer-reminder">FTP 傳檔作業完成後，請務必電話或傳真告知，以避免檔案疏失錯漏。</p></section>
    <section class="ftp-steps" aria-labelledby="ftp-steps-title"><h2 id="ftp-steps-title">FTP 操作步驟</h2><article><div class="step-copy"><span>01</span><h3>安裝軟體後執行</h3></div><img src="/images/file-transfer/ftp-step-1.jpg" alt="FileZilla 操作步驟一"></article><article><div class="step-copy"><span>02</span><h3>輸入主機與帳號資訊後快速連線</h3><p>主機輸入：ftp.imagecopy.com.tw，再輸入使用者名稱與密碼，按下「快速連線」。</p></div><img src="/images/file-transfer/ftp-step-2.jpg" alt="FileZilla 操作步驟二"></article><article><div class="step-copy"><span>03</span><h3>拖曳檔案至上傳視窗</h3><p>將需要上傳的檔案拖曳至上傳視窗，即可開始傳輸。</p></div><img src="/images/file-transfer/ftp-step-3.jpg" alt="FileZilla 操作步驟三"></article></section>
    <section class="email-checklist" aria-labelledby="email-checklist-title"><h2 id="email-checklist-title">以電子郵件傳送列印文件時，請註明</h2><ol><li>您的姓名與電話</li><li>取件時間</li><li>列印尺寸：B5、A4、B4、A3、A2、A1、A0 或特殊尺寸</li><li>列印份數</li><li>列印內容：彩色、黑白、單面、雙面、插頁方式、紙質、封面紙</li><li>裝訂方式：膠裝、書背、上光、活頁、精裝、平訂</li><li>檔案格式與製作時使用的軟體名稱</li></ol><p>檔案傳輸完成後，請立即來電告知，謝謝您的合作與愛護。</p></section>
  </section>
</template>

<style scoped>
.transfer-page{padding-top:68px;padding-bottom:100px}.transfer-heading{display:flex;justify-content:space-between;align-items:end;gap:30px;margin-bottom:45px}.transfer-heading h1{margin:0;font-size:42px}.transfer-heading p{max-width:520px;margin:0;color:var(--muted)}.ftp-intro{display:flex;justify-content:space-between;align-items:center;gap:30px;padding:28px 30px;border-top:5px solid #d51f26;background:#f7f7f4}.ftp-intro h2,.ftp-intro p{margin:0}.ftp-intro h2{font-size:25px}.ftp-intro p{color:var(--muted);margin-top:5px}.ftp-intro .btn{flex:0 0 auto;transition:background-color .22s ease,border-color .22s ease}.ftp-intro .btn:hover{background:#c94e26;border-color:#c94e26}.transfer-notes,.ftp-steps,.email-checklist{margin-top:55px}.transfer-notes h2,.ftp-steps>h2,.email-checklist h2{font-size:26px;margin:0 0 20px}.transfer-notes ol,.email-checklist ol{display:grid;gap:8px;margin:0;padding-left:24px;color:var(--muted)}.transfer-notes li::marker,.email-checklist li::marker{color:#d51f26;font-weight:700}.transfer-reminder{margin:22px 0 0;padding:15px 18px;background:#fff3f3;color:#a61c22;font-weight:700}.ftp-steps{display:grid;gap:38px}.ftp-steps>h2{margin-bottom:0}.ftp-steps article{border-top:1px solid var(--line);padding-top:22px}.step-copy{display:grid;grid-template-columns:50px 1fr;column-gap:16px;align-items:start;margin-bottom:20px}.step-copy span{grid-row:span 2;color:#d51f26;font:30px Oswald}.step-copy h3{margin:0;font-size:21px}.step-copy p{grid-column:2;margin:5px 0 0;color:var(--muted)}.ftp-steps img{display:block;width:100%;max-width:812px;margin:auto;border:1px solid var(--line)}.email-checklist{border-top:5px solid #d51f26;padding:30px;background:#fff7f7}.email-checklist p{margin:20px 0 0;color:#a61c22;font-weight:700}@media(max-width:700px){.transfer-page{padding-top:48px;padding-bottom:70px}.transfer-heading,.ftp-intro{display:block}.transfer-heading h1{font-size:36px}.transfer-heading p{margin-top:10px}.ftp-intro .btn{margin-top:20px}.transfer-notes,.ftp-steps,.email-checklist{margin-top:42px}.ftp-intro{padding:24px}.ftp-steps img{width:100%}}
</style>
